name: Build Docker image
on: [push]

jobs:
  build:
    name: Build Docker image with base node image
    runs-on: ubuntu-latest
    steps:
      - name: Build base node image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: swarthy/node-dev
          build_args: IMAGE_VERSION=14
          tags: 14
      - name: Build alpine node image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: swarthy/node-dev
          build_args: IMAGE_VERSION=14
          dockerfile: Dockerfile-alpine
          tags: 14-alpine
